import firstImage from '../assets/images/home/first.jpg';
import NorthEastArrow from '../assets/images/home/northEastArrow.svg';
import checkbg from '../assets/images/home/checkbg.svg'
import ownVision from '../assets/images/home/ownVision.png'
import fabricImg from '../assets/images/home/fabric_color_size.png';
import femaleModel from '../assets/images/home/femaleModel.svg';
import maleModal from '../assets/images/home/maleModal.svg';
import testimonialbg from '../assets/images/home/testimonialbg.svg';
import manProfessional from '../assets/images/home/manProfessional.jpg';
import femaleProfessional from '../assets/images/home/femaleProfessional.jpg';
import doubleSideArrow from '../assets/images/home/doubleSideArrow.svg';
import uploadModal from '../assets/images/home/uploadModal.jpg';
import selectCategory from '../assets/images/home/selectCategory.jpg';
import processing from '../assets/images/home/processing.jpg';
import givePrompt from '../assets/images/home/givePrompt.jpg';
import garment from '../assets/images/home/garment.jpg';
import wardrobe from '../assets/images/home/wardrobe.jpg';
import logo from '../assets/images/home/logo.png'
import chooseModal from '../assets/images/home/chooseModal.jpg'
import application1 from '../assets/images/home/application1.jpeg';
import application2 from '../assets/images/home/application2.jpg';
import application3 from '../assets/images/home/application3.jpg';
import application4 from '../assets/images/home/application4.jpg';
import input from '../assets/images/home/input.jpg';
import output from '../assets/images/home/output.png';
import desktopView from '../assets/images/home/Desktop-view.jpg'
import mobileView from '../assets/images/home/Mobile-view.jpg'
import tabletView from '../assets/images/home/Tablet-view.jpg'

export {checkbg, NorthEastArrow, firstImage, ownVision, fabricImg, maleModal, femaleModel, testimonialbg, manProfessional, femaleProfessional, doubleSideArrow, uploadModal, selectCategory, processing, givePrompt, garment, wardrobe, logo, chooseModal, application1, application2, application3, application4, input, output, desktopView, mobileView, tabletView};
